# Generated by Django 3.2.7 on 2025-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLproject2', '0002_uploadtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
